#!/bin/bash
# This script should be run when opening the project in a new environment
# so that the Xlator plugin is properly set up with the project.
# Specifically, .xlator.local.env needs to be generated with the CLAUDE_PLUGIN_ROOT variable.

set -e

# Resolve the user's project root (where xlator.conf lives)
if git rev-parse --show-toplevel >/dev/null 2>&1; then
    PROJECT_ROOT="$(git rev-parse --show-toplevel)"
elif [ -f "$PWD/xlator.conf" ]; then
    PROJECT_ROOT="$PWD"
else
    echo "Error: Cannot find project root. Run /xl:setup to create xlator.conf." >&2
    exit 1
fi

if [ ! -f "$PROJECT_ROOT/xlator.conf" ]; then
    echo "Error: xlator.conf not found at $PROJECT_ROOT/xlator.conf" >&2
    echo "Run /xl:setup in Claude Code to configure this project." >&2
    exit 1
fi
# Load DOMAINS_DIR env variable
source "$PROJECT_ROOT/xlator.conf"

set_up_claude_plugin() {
    echo "😉 0. Installing Claude and configuring Xlator plugin (writing .xlator.local.env)..."
    if ! command -v claude >/dev/null 2>&1; then
        # TODO: move this to Dockerfile
        curl -fsSL https://claude.ai/install.sh | bash
        export PATH="$HOME/.local/bin:$PATH"
    fi

    # Don't need to authenticate claude to add plugins
    # Can append '#tagOrBranch' to the URL to specify a version, e.g. 'main' or 'v1.2.3'
    claude plugin marketplace add https://github.com/navapbc/lockpicks-xlator-plugin.git
    claude plugin install xl@lockpicks-marketplace --scope project

    # Helpful for code generation
    claude plugin marketplace add https://github.com/EveryInc/every-marketplace.git
    claude plugin install compound-engineering@compound-engineering-plugin --scope project

    # CLAUDE_PLUGIN_ROOT is an environment variable set by Claude Code to the absolute path of
    # a plugin's installation directory. It is intended to be available for hook commands but
    # not other commands. Make it available for other contexts (like the shell scripts and slash commands).
    CLAUDE_PLUGIN_ROOT=$(claude plugin list --json | uv run python -c 'import sys, json
plugins = json.load(sys.stdin)
xl = next((p for p in plugins if p["id"].startswith("xl@")), None)
print(xl["installPath"] if xl else "", end="")
')
    if [ -z "$CLAUDE_PLUGIN_ROOT" ]; then
        echo "Error: Failed to determine CLAUDE_PLUGIN_ROOT from 'claude plugin list'" >&2
        exit 10
    fi
    {
        echo "# This file is automatically generated by xlator's setup script. Needed for Xlator to function properly."
        echo "export CLAUDE_PLUGIN_ROOT='${CLAUDE_PLUGIN_ROOT}'"
    } > "$PROJECT_ROOT/.xlator.local.env"
}

cmd_setup_final() {
    date
    echo "😀 2. Creating Python virtual environment and installing dependencies..."
    # 'uv sync' installs the version specified in .python-version in a venv
    uv sync
    . .venv/bin/activate

    date
    echo "😅 3. Initializing opam (if needed; this can take 10 minutes)..."
    if [ ! -d "~/.opam" ]; then
        # Catala supports OCaml versions from 4.14.0 up to 5.4.X.
        opam init -y -a -c 5.4.1
    fi
    eval "$(opam env)"

    date
    echo "😄 4. Installing Catala/clerk (if missing; this can take 10 minutes)..."
    if ! command -v clerk >/dev/null; then
        opam update && opam install -y catala.1.1.0
    fi

    date

    echo "🤓 6. Creating symlink $DOMAINS_DIR/.plugin to the Xlator plugin folder..."
    # This allows a power user to run scripts directly.
    ln -snf "$CLAUDE_PLUGIN_ROOT/xlator" .
    # This provides easy access to the Xlator plugin folder to understand how it works.
    ln -snf "$CLAUDE_PLUGIN_ROOT" .plugin

    date
    echo "🤩 Setup complete"
}


set_up_claude_plugin

mkdir -p "$PROJECT_ROOT/$DOMAINS_DIR"
cd "$PROJECT_ROOT/$DOMAINS_DIR"
echo "1. Copying files to $PROJECT_ROOT/$DOMAINS_DIR ..."
for F in .gitignore CLAUDE.md mise.toml pyproject.toml .python-version uv.lock; do
    if [ -f "$F" ]; then
        echo "Overriding: $DOMAINS_DIR/$F"
    fi
    cp -v "$CLAUDE_PLUGIN_ROOT/$F" .
done

cmd_setup_final
