#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["pyyaml>=6.0"]
# ///
"""
xlator record-tier-manifest: write a per-tier SHA manifest for a domain.

Used by generation skills at their successful-write boundary to record the
SHAs of upstream files the downstream tier depends on. The freshness check
(`xlator check-freshness`) later compares these recorded SHAs against the
current working tree.

This tool covers two tiers:
- `--tier guidance` writes specs/guidance/.facets-manifest.yaml, recording
  SHAs of every policy_facets/ file (input-index.yaml, compressed/**/*.md,
  computations/**/*.md.yaml).
- `--tier tests` writes specs/tests/.civil-manifest.yaml, recording SHAs of
  every specs/*.civil.yaml file.

The civil tier is intentionally not exposed here: /extract-ruleset Step 5
and /update-ruleset Step 7 author the consumed_guidance[] block inline in
specs/extraction-manifest.yaml directly, sourcing SHAs from the new shared
procedure SP-LoadGuidanceShas in xl-plugin/core/ruleset-shared.md.

Usage:
    xlator record-tier-manifest <domain> --tier {guidance|tests}

Exit codes:
    0 — manifest written successfully
    2 — environment/usage error (DOMAINS_FULLPATH unset, domain dir missing,
        invalid arguments)

SHA fallback: when `git hash-object` exits non-zero or git is unavailable,
the file's entry records the literal string "untracked", mirroring the
existing SP-LoadInputIndex contract at xl-plugin/core/ruleset-shared.md:617.
"""

from __future__ import annotations

import argparse
import datetime
import os
import subprocess
import sys
from pathlib import Path

import yaml


_POLICY_FACETS = "policy_facets"
_INPUT_INDEX = "policy_facets/input-index.yaml"
_COMPRESSED = "policy_facets/compressed"
_COMPUTATIONS = "policy_facets/computations"
_SPECS = "specs"
_GUIDANCE = "specs/guidance"
_TESTS = "specs/tests"

_GUIDANCE_MANIFEST = "specs/guidance/.facets-manifest.yaml"
_TESTS_MANIFEST = "specs/tests/.civil-manifest.yaml"


def _git_sha(domain_dir: Path, abs_path: Path) -> str:
    """git hash-object <path>; SHA of current file content (working-tree blob).

    Returns 'untracked' when git or hash-object cannot run. Mirrors the
    fallback contract in xl-plugin/core/ruleset-shared.md:617.
    """
    try:
        result = subprocess.run(
            ["git", "hash-object", str(abs_path)],
            cwd=str(domain_dir),
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return "untracked"
    sha = result.stdout.strip()
    return sha or "untracked"


def _enumerate_guidance_upstream(domain_dir: Path) -> list[Path]:
    """Return all policy_facets/ files that downstream guidance derives from.

    Includes input-index.yaml plus every file under compressed/ and computations/.
    Returns paths in sorted (deterministic) order.
    """
    paths: list[Path] = []

    index = domain_dir / _INPUT_INDEX
    if index.is_file():
        paths.append(index)

    compressed = domain_dir / _COMPRESSED
    if compressed.is_dir():
        paths.extend(sorted(compressed.rglob("*.md")))

    computations = domain_dir / _COMPUTATIONS
    if computations.is_dir():
        paths.extend(sorted(computations.rglob("*.md.yaml")))

    return paths


def _enumerate_tests_upstream(domain_dir: Path) -> list[Path]:
    """Return all specs/*.civil.yaml files that downstream tests derive from.

    Returns paths in sorted (deterministic) order.
    """
    specs = domain_dir / _SPECS
    if not specs.is_dir():
        return []
    return sorted(specs.glob("*.civil.yaml"))


def _record_manifest(
    domain_dir: Path,
    upstream_paths: list[Path],
    manifest_rel: str,
    tier_name: str,
) -> Path:
    """Compute per-file SHAs and write the tier manifest atomically.

    Returns the manifest path. Empty upstream produces an empty `files: {}` map
    rather than a missing file — downstream consumers distinguish between
    `*_manifest_missing` (no file) and "tier has nothing upstream yet" (empty
    files map).
    """
    files_map: dict[str, str] = {}
    for path in upstream_paths:
        rel = path.relative_to(domain_dir).as_posix()
        files_map[rel] = _git_sha(domain_dir, path)

    manifest_path = domain_dir / manifest_rel
    manifest_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "recorded_at": datetime.datetime.now(datetime.UTC).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        ),
        "files": files_map,
    }
    header = (
        f"# Auto-generated by xlator record-tier-manifest --tier {tier_name};\n"
        f"# do not edit manually. Records the SHA of each upstream file at the\n"
        f"# time the downstream tier was last touched.\n"
    )

    tmp = manifest_path.with_suffix(manifest_path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(payload, f, default_flow_style=False, sort_keys=True)
    os.replace(tmp, manifest_path)
    return manifest_path


def cmd_record(domain_dir: Path, tier: str) -> Path:
    """Write the manifest for `tier` in `domain_dir`. Returns the manifest path."""
    if tier == "guidance":
        upstream = _enumerate_guidance_upstream(domain_dir)
        return _record_manifest(domain_dir, upstream, _GUIDANCE_MANIFEST, "guidance")
    if tier == "tests":
        upstream = _enumerate_tests_upstream(domain_dir)
        return _record_manifest(domain_dir, upstream, _TESTS_MANIFEST, "tests")
    # argparse choices= should prevent ever reaching here.
    raise ValueError(f"unsupported tier: {tier!r}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Write a per-tier SHA manifest for a domain. Used by generation "
            "skills at their write boundary to record what upstream they "
            "depend on, so xlator check-freshness can later detect drift."
        ),
        epilog=(
            "The civil tier is intentionally not supported here. The civil "
            "manifest (consumed_guidance[] block in specs/extraction-manifest.yaml) "
            "is authored by /extract-ruleset Step 5 and refreshed by "
            "/update-ruleset Step 7 inline, sourcing SHAs from the shared "
            "procedure SP-LoadGuidanceShas in xl-plugin/core/ruleset-shared.md."
        ),
    )
    parser.add_argument("domain", help="Domain name (e.g. snap, ak_doh)")
    parser.add_argument(
        "--tier",
        required=True,
        choices=["guidance", "tests"],
        help="Which tier's manifest to write.",
    )
    args = parser.parse_args()

    domains_root = os.environ.get("DOMAINS_FULLPATH")
    if not domains_root:
        print("Error: DOMAINS_FULLPATH not set in environment.", file=sys.stderr)
        sys.exit(2)
    domain_dir = Path(domains_root) / args.domain
    if not domain_dir.is_dir():
        print(f"Error: Domain directory not found: {domain_dir}", file=sys.stderr)
        sys.exit(2)

    manifest_path = cmd_record(domain_dir, args.tier)
    print(f"Wrote {manifest_path.relative_to(domain_dir).as_posix()}")
    sys.exit(0)


if __name__ == "__main__":
    main()
