# /// script
# requires-python = ">=3.14"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Tests for emit_per_file_yaml.py — covers post-v9.0.0 per-file YAML emission.

Run: uv run xl-plugin/tools/test_emit_per_file_yaml.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

sys.path.insert(0, os.path.dirname(__file__))

import emit_per_file_yaml  # noqa: E402


# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------


def _minimal_payload(dst: Path, source_rel: str = "input/policy_docs/a.md") -> dict:
    return {
        "destination": str(dst),
        "source_rel": source_rel,
        "sections": [],
    }


def _payload_with_one_computation(dst: Path) -> dict:
    return {
        "destination": str(dst),
        "source_rel": "input/policy_docs/a.md",
        "sections": [
            {
                "heading": "# Income",
                "summary": "Income rules.",
                "tags": ["income"],
                "computations": [
                    {
                        "description": "Sum earned and unearned income.",
                        "expr_hint": "gross_income = earned_income + unearned_income",
                    },
                ],
            },
        ],
    }


# ---------------------------------------------------------------------------
# Happy path / round-trip
# ---------------------------------------------------------------------------


def test_emitted_yaml_is_top_level_map_with_only_sections():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_computation(dst))
        loaded = yaml.safe_load(dst.read_text())
        assert isinstance(loaded, dict)
        assert set(loaded.keys()) == {"sections"}


def test_emitted_yaml_has_preamble_with_source_path():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_computation(dst))
        text = dst.read_text()
        assert "# Auto-generated by /extract-computations — do not edit manually" in text
        assert "# Source: input/policy_docs/a.md" in text


def test_round_trip_preserves_sections_structure():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        assert loaded["sections"] == payload["sections"]


def test_empty_sections_list_is_valid():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_minimal_payload(dst))
        assert dst.exists()


# ---------------------------------------------------------------------------
# expr_hint shape (post-v9.0.0)
# ---------------------------------------------------------------------------


def test_expr_hint_assignment_form_round_trips_verbatim():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        comp = loaded["sections"][0]["computations"][0]
        assert comp["expr_hint"] == "gross_income = earned_income + unearned_income"


def test_descriptive_only_computation_omits_expr_hint():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = {
            "destination": str(dst),
            "source_rel": "input/policy_docs/a.md",
            "sections": [
                {
                    "heading": "# Eligibility",
                    "summary": "Categorical eligibility rules.",
                    "tags": ["eligibility"],
                    "computations": [
                        {"description": "Households receiving SSI are categorically eligible."},
                    ],
                },
            ],
        }
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        comp = loaded["sections"][0]["computations"][0]
        assert "expr_hint" not in comp


def test_expr_hint_with_function_call_on_rhs_is_accepted():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = "total = sum(items)"
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        comp = loaded["sections"][0]["computations"][0]
        assert comp["expr_hint"] == "total = sum(items)"


def test_expr_hint_bare_expression_no_equals_is_rejected():
    """Legacy bare-expression form (no `=`) is rejected on emission."""
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = "earned_income + unearned_income"
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            msg = str(exc)
            assert "expr_hint" in msg
            assert "=" in msg
            assert "output_name" in msg
        else:
            raise AssertionError("expected ValidationError for bare-expression expr_hint")


def test_expr_hint_empty_lhs_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = " = a + b"
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "expr_hint" in str(exc)
            assert "empty output name" in str(exc)
        else:
            raise AssertionError("expected ValidationError for empty LHS")


def test_expr_hint_empty_rhs_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = "out = "
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "expr_hint" in str(exc)
            assert "empty expression" in str(exc)
        else:
            raise AssertionError("expected ValidationError for empty RHS")


def test_expr_hint_non_snake_case_lhs_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = "BadName = a + b"
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            msg = str(exc)
            assert "expr_hint" in msg
            assert "snake_case" in msg
        else:
            raise AssertionError("expected ValidationError for non-snake_case LHS")


def test_expr_hint_lhs_starting_with_digit_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = "1foo = bar"
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "snake_case" in str(exc)
        else:
            raise AssertionError("expected ValidationError for digit-leading LHS")


def test_expr_hint_lhs_with_hyphen_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = "gross-income = a + b"
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "snake_case" in str(exc)
        else:
            raise AssertionError("expected ValidationError for hyphen in LHS")


def test_expr_hint_null_is_treated_as_absent():
    """None-valued expr_hint round-trips as absent (descriptive-only path)."""
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = None
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        comp = loaded["sections"][0]["computations"][0]
        assert "expr_hint" not in comp


# ---------------------------------------------------------------------------
# variables: block (post-observations-list schema)
# ---------------------------------------------------------------------------


def test_variables_block_round_trips_with_policy_phrase():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["variables"] = {
            "gross_income": {"policy_phrase": "gross monthly income"},
            "earned_income": {"policy_phrase": "earned income"},
        }
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        assert loaded["sections"][0]["variables"] == {
            "gross_income": {"policy_phrase": "gross monthly income"},
            "earned_income": {"policy_phrase": "earned income"},
        }


def test_variables_block_round_trips_with_empty_entry():
    """Variables observed in a section without a verbatim phrase emit as `<var>: {}`."""
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["variables"] = {
            "gross_income": {"policy_phrase": "gross monthly income"},
            "deductions": {},
        }
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        assert loaded["sections"][0]["variables"]["deductions"] == {}
        assert "policy_phrase" not in loaded["sections"][0]["variables"]["deductions"]


def test_variables_block_strips_none_policy_phrase():
    """None-valued policy_phrase round-trips as absent."""
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["variables"] = {
            "deductions": {"policy_phrase": None},
        }
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        assert "policy_phrase" not in loaded["sections"][0]["variables"]["deductions"]


def test_payload_without_variables_block_emits_unchanged():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_computation(dst))
        loaded = yaml.safe_load(dst.read_text())
        assert "variables" not in loaded["sections"][0]


def test_variables_not_a_dict_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["variables"] = ["gross_income"]
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "variables" in str(exc)
            assert "map" in str(exc)
        else:
            raise AssertionError("expected ValidationError for non-dict variables block")


def test_variables_entry_not_a_dict_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["variables"] = {"gross_income": "not a dict"}
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "gross_income" in str(exc)
        else:
            raise AssertionError("expected ValidationError for non-dict variables entry")


def test_variables_non_snake_case_key_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["variables"] = {"GrossIncome": {"policy_phrase": "x"}}
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "snake_case" in str(exc)
        else:
            raise AssertionError("expected ValidationError for non-snake_case variable key")


def test_variables_policy_phrase_non_string_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["variables"] = {"gross_income": {"policy_phrase": 42}}
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "policy_phrase" in str(exc)
            assert "string" in str(exc)
        else:
            raise AssertionError("expected ValidationError for non-string policy_phrase")


def test_variables_policy_phrase_empty_string_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["variables"] = {"gross_income": {"policy_phrase": ""}}
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "policy_phrase" in str(exc)
            assert "non-empty" in str(exc)
        else:
            raise AssertionError("expected ValidationError for empty policy_phrase")


# ---------------------------------------------------------------------------
# Atomic write
# ---------------------------------------------------------------------------


def test_destination_does_not_get_partial_content_on_validation_failure():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        dst.write_text("PRIOR CONTENT\n")
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = "no equals here"
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError:
            pass
        assert dst.read_text() == "PRIOR CONTENT\n"


def test_destination_creates_intermediate_directories():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "deeply" / "nested" / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_computation(dst))
        assert dst.exists()


# ---------------------------------------------------------------------------
# CLI / stdin contract
# ---------------------------------------------------------------------------


def test_cli_reads_json_from_stdin_and_writes_yaml():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        result = subprocess.run(
            [sys.executable, os.path.join(os.path.dirname(__file__), "emit_per_file_yaml.py")],
            input=json.dumps(payload),
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, f"stderr: {result.stderr}"
        assert dst.exists()


def test_cli_exits_nonzero_on_validation_error():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_computation(dst)
        payload["sections"][0]["computations"][0]["expr_hint"] = "no equals"
        result = subprocess.run(
            [sys.executable, os.path.join(os.path.dirname(__file__), "emit_per_file_yaml.py")],
            input=json.dumps(payload),
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode != 0
        assert "expr_hint" in result.stderr


# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    failed = 0
    passed = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
            except AssertionError as exc:
                failed += 1
                print(f"FAIL {name}: {exc}")
            except Exception as exc:
                failed += 1
                print(f"ERROR {name}: {type(exc).__name__}: {exc}")
            else:
                passed += 1
                print(f"ok {name}")
    print(f"\n{passed} passed, {failed} failed")
    sys.exit(1 if failed else 0)
