# /// script
# requires-python = ">=3.14"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Tests for naming_defaults.py — covers U4 merge tool scenarios.

Run: uv run xl-plugin/tools/test_naming_defaults.py
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

import yaml

sys.path.insert(0, os.path.dirname(__file__))

import naming_defaults  # noqa: E402


# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


def _make_domain(tmp: Path, name: str = "test_dom") -> Path:
    """Create a domain dir with the standard policy_facets/computations/ tree."""
    domain = tmp / name
    (domain / "policy_facets" / "computations").mkdir(parents=True)
    (domain / "input" / "policy_docs").mkdir(parents=True)
    (domain / "specs").mkdir(parents=True)
    return domain


def _write_per_file(
    domain: Path,
    rel: str,
    naming_manifest: dict | None,
    sections: list,
) -> Path:
    """Write a per-file map-shape YAML at policy_facets/computations/<rel>.yaml.

    `rel` is the source rel like "eligibility.md"; destination is
    `policy_facets/computations/<rel>.yaml` (suffix matches the per-file convention).
    Pass `naming_manifest=None` to omit the field entirely (partial-shape file).

    Auto-migration to the new schema: each variable entry that uses the legacy
    `source_section:` field gets the field renamed to `section:`, and entries
    that lack `source_doc:` get one auto-injected to match the file location
    (`input/policy_docs/<rel>.md`). Tests that need to exercise legacy or
    drift behavior bypass this helper and write raw YAML directly.
    """
    if naming_manifest is not None:
        variables = naming_manifest.get("variables") or {}
        if isinstance(variables, dict):
            full_path = f"input/policy_docs/{rel}"
            for entry in variables.values():
                if not isinstance(entry, dict):
                    continue
                if "source_section" in entry and "section" not in entry:
                    entry["section"] = entry.pop("source_section")
                if "source_doc" not in entry:
                    entry["source_doc"] = full_path
    dst = domain / "policy_facets" / "computations" / f"{rel}.yaml"
    dst.parent.mkdir(parents=True, exist_ok=True)
    body: dict = {}
    if naming_manifest is not None:
        body["naming_manifest"] = naming_manifest
    body["sections"] = sections
    with dst.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by /extract-computations — do not edit manually\n")
        f.write(f"# Source: input/policy_docs/{rel}\n\n")
        yaml.safe_dump(body, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    return dst


def _write_specs(domain: Path, payload: dict) -> Path:
    path = domain / "specs" / "naming-manifest.yaml"
    with path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(payload, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    return path


def _read_defaults(domain: Path) -> dict:
    path = domain / "policy_facets" / "naming-defaults.yaml"
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _read_per_file(domain: Path, rel: str) -> dict:
    path = domain / "policy_facets" / "computations" / f"{rel}.yaml"
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


# ---------------------------------------------------------------------------
# Normalizer
# ---------------------------------------------------------------------------


def test_normalize_lowercases_strips_articles_punct_collapse_ws():
    """Normalizer collapses casing, articles, punctuation, and whitespace runs."""
    base = naming_defaults.normalize_phrase("gross monthly income")
    assert base == "gross monthly income"
    assert naming_defaults.normalize_phrase("  Gross Monthly Income.") == base
    assert naming_defaults.normalize_phrase("the gross monthly income") == base
    assert naming_defaults.normalize_phrase("GROSS MONTHLY INCOME") == base
    assert naming_defaults.normalize_phrase("a gross   monthly\tincome") == base
    assert naming_defaults.normalize_phrase("an Gross Monthly Income!") == base


# ---------------------------------------------------------------------------
# Happy paths
# ---------------------------------------------------------------------------


def test_ae1_two_files_disagree_shortest_wins():
    """AE1: file A has gross_income, file B has monthly_gross — same phrase.
    canonical = gross_income (tied freq=1, shortest wins); B's variables: rewritten."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))

        _write_per_file(
            domain, "eligibility.md",
            naming_manifest={
                "variables": {
                    "gross_income": {
                        "policy_phrase": "gross monthly income",
                        "source_section": "§1.2",
                    },
                },
            },
            sections=[{
                "heading": "# Income",
                "summary": "...",
                "tags": ["income"],
                "computations": [{"description": "...", "variables": ["gross_income"]}],
            }],
        )
        _write_per_file(
            domain, "income.md",
            naming_manifest={
                "variables": {
                    "monthly_gross": {
                        "policy_phrase": "gross monthly income",
                        "source_section": "§2.1",
                    },
                },
            },
            sections=[{
                "heading": "# Earned Income",
                "summary": "...",
                "tags": ["income"],
                "computations": [{"description": "...", "variables": ["monthly_gross"]}],
            }],
        )

        summary = naming_defaults.cmd_build(domain)

        defaults = _read_defaults(domain)
        assert "gross_income" in defaults["variables"]
        entry = defaults["variables"]["gross_income"]
        assert entry["source_doc"] == "input/policy_docs/eligibility.md"
        assert entry["section"] == "§1.2"
        assert entry["synonyms"] == [{
            "name": "monthly_gross",
            "source_doc": "input/policy_docs/income.md",
            "section": "§2.1",
        }]
        assert entry["policy_phrase"] == "gross monthly income"
        # File B's variables list rewritten to canonical.
        b = _read_per_file(domain, "income.md")
        assert b["sections"][0]["computations"][0]["variables"] == ["gross_income"]
        # File A unchanged on canonical name.
        a = _read_per_file(domain, "eligibility.md")
        assert a["sections"][0]["computations"][0]["variables"] == ["gross_income"]
        assert summary["merged"] == 1
        assert summary["synonyms_collapsed"] == 1
        assert summary["files_rewritten"] == 1


def test_ae2_specs_overrides_frequency():
    """AE2: specs has monthly_gross_income; files use gross_income, monthly_gross —
    canonical = monthly_gross_income (specs authority); per-file lists rewritten."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))

        _write_specs(domain, {
            "version": "1.0",
            "inputs": {
                "Household": {
                    "monthly_gross_income": {
                        "policy_phrase": "gross monthly income",
                        "source_doc": "eligibility.md",
                        "section": "§1.2",
                    },
                },
            },
        })
        _write_per_file(
            domain, "eligibility.md",
            naming_manifest={
                "variables": {
                    "gross_income": {
                        "policy_phrase": "gross monthly income",
                        "source_section": "§1.2",
                    },
                },
            },
            sections=[{
                "heading": "# Income",
                "summary": "...",
                "tags": [],
                "computations": [{"description": "...", "variables": ["gross_income"]}],
            }],
        )
        _write_per_file(
            domain, "income.md",
            naming_manifest={
                "variables": {
                    "monthly_gross": {
                        "policy_phrase": "gross monthly income",
                        "source_section": "§2.1",
                    },
                },
            },
            sections=[{
                "heading": "# Earned",
                "summary": "...",
                "tags": [],
                "computations": [{"description": "...", "variables": ["monthly_gross"]}],
            }],
        )

        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "monthly_gross_income" in defaults["variables"]
        entry = defaults["variables"]["monthly_gross_income"]
        # Specs-picked canonical never observed in any per-file file → fall back
        # to specs source_doc/section (basename normalized to full path).
        assert entry["source_doc"] == "input/policy_docs/eligibility.md"
        assert entry["section"] == "§1.2"
        # Specs-fallback branch: every observation becomes a synonym row.
        assert entry["synonyms"] == [
            {
                "name": "gross_income",
                "source_doc": "input/policy_docs/eligibility.md",
                "section": "§1.2",
            },
            {
                "name": "monthly_gross",
                "source_doc": "input/policy_docs/income.md",
                "section": "§2.1",
            },
        ]
        a = _read_per_file(domain, "eligibility.md")
        b = _read_per_file(domain, "income.md")
        assert a["sections"][0]["computations"][0]["variables"] == ["monthly_gross_income"]
        assert b["sections"][0]["computations"][0]["variables"] == ["monthly_gross_income"]


def test_three_files_agree_self_synonyms_no_rewrites():
    """Three files agree on the canonical name — top-level source from the first
    (alphabetical) observation; the other two become self-synonym rows. No
    file rewrites; synonyms_collapsed stays 0 (zero non-canonical names)."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        for rel in ("a.md", "b.md", "c.md"):
            _write_per_file(
                domain, rel,
                naming_manifest={"variables": {"gross_income": {
                    "policy_phrase": "gross monthly income", "source_section": "§1",
                }}},
                sections=[{"heading": "# h", "summary": "", "tags": [],
                           "computations": [{"description": "", "variables": ["gross_income"]}]}],
            )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert entry["source_doc"] == "input/policy_docs/a.md"
        assert entry["section"] == "§1"
        # Other two observations of the same canonical name → self-synonym rows.
        assert entry["synonyms"] == [
            {"name": "gross_income", "source_doc": "input/policy_docs/b.md", "section": "§1"},
            {"name": "gross_income", "source_doc": "input/policy_docs/c.md", "section": "§1"},
        ]
        assert summary["files_rewritten"] == 0
        # Zero unique non-canonical names → synonyms_collapsed = 0 even though
        # synonyms list has 2 self-synonym rows.
        assert summary["synonyms_collapsed"] == 0


def test_single_file():
    """Single per-file file → canonical = its name; no synonyms; no rewrites."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "gross_income" in defaults["variables"]
        assert "synonyms" not in defaults["variables"]["gross_income"]
        assert summary["files_rewritten"] == 0


def test_zero_files_writes_empty_variables_map():
    """Zero per-file files → naming-defaults.yaml with variables: {} and preamble."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        summary = naming_defaults.cmd_build(domain)
        path = domain / "policy_facets" / "naming-defaults.yaml"
        assert path.exists()
        text = path.read_text(encoding="utf-8")
        assert text.startswith("# Auto-generated by xlator naming-defaults --build")
        defaults = yaml.safe_load(text) or {}
        assert defaults["variables"] == {}
        assert summary["merged"] == 0


# ---------------------------------------------------------------------------
# role_hint resolution
# ---------------------------------------------------------------------------


def test_role_hint_carried_from_synonym_when_canonical_absent():
    """One file has role_hint: computed, another omits → canonical entry has computed."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # gross_income (no hint) wins shortest tie over monthly_gross (computed).
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"monthly_gross": {
                "policy_phrase": "gross monthly income",
                "role_hint": "computed",
                "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["monthly_gross"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert entry["role_hint"] == "computed"


def test_role_hint_disagreement_prefers_computed():
    """Two files disagree — input vs computed — canonical gets computed."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income",
                "role_hint": "input",
                "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"monthly_gross": {
                "policy_phrase": "gross monthly income",
                "role_hint": "computed",
                "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["monthly_gross"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert entry["role_hint"] == "computed"


# ---------------------------------------------------------------------------
# Defensive reads
# ---------------------------------------------------------------------------


def test_malformed_naming_manifest_skipped_with_warning():
    """File whose naming_manifest is not a dict → log warning, skip, exit 0 if anyone usable."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # A is malformed (naming_manifest is a list, not a map).
        bad = domain / "policy_facets" / "computations" / "a.md.yaml"
        bad.write_text(
            "naming_manifest:\n  - this is wrong\nsections: []\n",
            encoding="utf-8",
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "gross_income" in defaults["variables"]
        # Errors are reported but exit remains 0 (one file usable).
        assert summary["merged"] >= 1


def test_partial_shape_no_naming_manifest_skipped_with_warning():
    """Map-shape file with sections: but no naming_manifest: → warning, treat as zero entries."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest=None,  # omit field entirely
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["foo"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "gross_income" in defaults["variables"]
        # Partial file's variables NOT canonicalized — left alone.
        a = _read_per_file(domain, "a.md")
        assert a["sections"][0]["computations"][0]["variables"] == ["foo"]
        assert summary["merged"] == 1


def test_unknown_variable_in_sections_logs_warning():
    """Per-file file's sections variables references a name not in naming_manifest.variables."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income", "ghost_var"]}]}],
        )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "gross_income" in defaults["variables"]
        # Unknown name left alone (canonicalization only for known names).
        a = _read_per_file(domain, "a.md")
        assert "ghost_var" in a["sections"][0]["computations"][0]["variables"]
        assert any("ghost_var" in str(e) for e in summary["errors"])


def test_legacy_list_shape_skipped_with_warning():
    """Legacy list-shape file (top-level YAML list) → warning, skip, do not crash."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        legacy = domain / "policy_facets" / "computations" / "legacy.md.yaml"
        legacy.write_text(
            "- heading: '# legacy'\n  summary: legacy\n  computations: []\n",
            encoding="utf-8",
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "gross_income" in defaults["variables"]
        assert summary["errors"]  # at least one warning recorded


# ---------------------------------------------------------------------------
# Specs flattening
# ---------------------------------------------------------------------------


def test_specs_flattening_inputs_and_computed():
    """Specs flattens inputs.<Entity>.<field> and flat computed.<name> by policy_phrase."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_specs(domain, {
            "version": "1.0",
            "inputs": {
                "Household": {
                    "foo_canonical": {
                        "policy_phrase": "the foo concept",
                        "source_doc": "eligibility.md",
                        "section": "§1",
                    },
                },
            },
            "computed": {
                "bar_canonical": {
                    "policy_phrase": "bar concept",
                    "source_doc": "eligibility.md",
                    "section": "§2",
                },
            },
        })
        _write_per_file(
            domain, "eligibility.md",
            naming_manifest={"variables": {
                "foo": {"policy_phrase": "the foo concept", "source_section": "§1"},
                "bar": {"policy_phrase": "bar concept", "source_section": "§2"},
            }},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["foo", "bar"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "foo_canonical" in defaults["variables"]
        assert "bar_canonical" in defaults["variables"]


def test_specs_multi_entity_collision_prefers_source_doc_in_glob():
    """Two specs entries with same policy_phrase but different entities — prefer the one
    whose source_doc matches a per-file file in the glob; alphabetical tiebreak by entity."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_specs(domain, {
            "version": "1.0",
            "inputs": {
                "Household": {
                    "gross_income_household": {
                        "policy_phrase": "gross monthly income",
                        "source_doc": "household.md",
                        "section": "§1",
                    },
                },
                "Applicant": {
                    "gross_income_applicant": {
                        "policy_phrase": "gross monthly income",
                        "source_doc": "applicant_form.md",
                        "section": "§1",
                    },
                },
            },
        })
        # Only applicant_form.md is in the per-file glob.
        _write_per_file(
            domain, "applicant_form.md",
            naming_manifest={"variables": {"gi": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gi"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        # Applicant's source_doc matches → canonical = gross_income_applicant.
        assert "gross_income_applicant" in defaults["variables"]
        assert "gross_income_household" not in defaults["variables"]


# ---------------------------------------------------------------------------
# Atomic write
# ---------------------------------------------------------------------------


def test_atomic_write_no_partial_file_on_failure(monkeypatch=None):
    """Mock os.replace to fail; verify no partial file at destination, tmp cleaned up.

    Uses a manual monkeypatch since pytest fixtures are not used in this file.
    """
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )

        defaults_path = domain / "policy_facets" / "naming-defaults.yaml"
        # Pre-write a known prior content so we can check it is preserved on failure.
        defaults_path.write_text("prior: content\n", encoding="utf-8")

        original_replace = os.replace
        calls: list = []

        def boom_replace(src, dst):
            calls.append((src, dst))
            # Only fail on the naming-defaults.yaml write, not per-file rewrites.
            if str(dst).endswith("naming-defaults.yaml"):
                raise OSError("simulated rename failure")
            return original_replace(src, dst)

        os.replace = boom_replace
        try:
            try:
                naming_defaults.cmd_build(domain)
            except OSError:
                pass
        finally:
            os.replace = original_replace

        # Prior content preserved (or removed cleanly) — never partial.
        assert defaults_path.read_text(encoding="utf-8") == "prior: content\n"
        # Tmp file should not be left behind.
        tmp_files = list((domain / "policy_facets").glob("naming-defaults.yaml.tmp"))
        assert tmp_files == []


# ---------------------------------------------------------------------------
# Idempotency, stability, churn
# ---------------------------------------------------------------------------


def test_idempotent_byte_identical_second_run():
    """Two consecutive --build runs produce byte-identical naming-defaults.yaml."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"monthly_gross": {
                "policy_phrase": "gross monthly income", "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["monthly_gross"]}]}],
        )

        naming_defaults.cmd_build(domain)
        first = (domain / "policy_facets" / "naming-defaults.yaml").read_bytes()
        # File B was rewritten on first run; second run shouldn't change anything.
        summary2 = naming_defaults.cmd_build(domain)
        second = (domain / "policy_facets" / "naming-defaults.yaml").read_bytes()
        assert first == second
        assert summary2["canonicals_changed"] == []
        assert summary2["files_rewritten"] == 0


def test_stability_heuristic_prefers_prior_canonical_on_tie():
    """Pure tie (frequency, length all equal) → prefer prior canonical when present."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # Two equal-length, equal-frequency names: "alpha_n" (7) and "beta_nn" (7).
        # Alphabetical tie-break would pick alpha_n; prior says beta_nn.
        prior_path = domain / "policy_facets" / "naming-defaults.yaml"
        prior_path.parent.mkdir(parents=True, exist_ok=True)
        prior_path.write_text(
            "# Auto-generated by xlator naming-defaults --build — do not edit manually\n"
            "variables:\n"
            "  beta_nn:\n"
            "    policy_phrase: \"the concept\"\n"
            "    source_doc: input/policy_docs/a.md\n"
            "    section: '§1'\n",
            encoding="utf-8",
        )
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"alpha_n": {
                "policy_phrase": "the concept", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["alpha_n"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"beta_nn": {
                "policy_phrase": "the concept", "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["beta_nn"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        # Stability heuristic kept beta_nn even though alpha_n is alphabetically first.
        assert "beta_nn" in defaults["variables"]
        assert defaults["variables"]["beta_nn"]["synonyms"] == [{
            "name": "alpha_n",
            "source_doc": "input/policy_docs/a.md",
            "section": "§1",
        }]


def test_no_prior_file_uses_alphabetical_tiebreak():
    """Same input but no prior file → algorithm's alphabetical tie-break wins."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"alpha_n": {
                "policy_phrase": "the concept", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["alpha_n"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"beta_nn": {
                "policy_phrase": "the concept", "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["beta_nn"]}]}],
        )
        # Don't write a prior file.
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "alpha_n" in defaults["variables"]


def test_canonical_churn_report():
    """Run 1 picks gross_income; modify file so canonical flips → churn list contains rename."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults1 = _read_defaults(domain)
        assert "gross_income" in defaults1["variables"]

        # Modify the file so it now uses a different name for the same phrase.
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"earned_pay": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["earned_pay"]}]}],
        )
        summary = naming_defaults.cmd_build(domain)
        defaults2 = _read_defaults(domain)
        assert "earned_pay" in defaults2["variables"]
        assert "gross_income" not in defaults2["variables"]
        churn = summary["canonicals_changed"]
        assert len(churn) == 1
        assert churn[0]["from"] == "gross_income"
        assert churn[0]["to"] == "earned_pay"


def test_canonicals_changed_empty_on_first_run():
    """When no prior naming-defaults.yaml exists → canonicals_changed is []."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        summary = naming_defaults.cmd_build(domain)
        assert summary["canonicals_changed"] == []


# ---------------------------------------------------------------------------
# Synonym retention (R8)
# ---------------------------------------------------------------------------


def test_synonyms_persist_in_output():
    """After canonicalization, synonyms: list persists in naming-defaults.yaml."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"monthly_gross": {
                "policy_phrase": "gross monthly income", "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["monthly_gross"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert defaults["variables"]["gross_income"]["synonyms"] == [{
            "name": "monthly_gross",
            "source_doc": "input/policy_docs/b.md",
            "section": "§2",
        }]


def test_dry_run_writes_nothing():
    """--dry-run: no naming-defaults.yaml produced, no per-file rewrites."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"monthly_gross": {
                "policy_phrase": "gross monthly income", "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["monthly_gross"]}]}],
        )
        before = _read_per_file(domain, "b.md")
        summary = naming_defaults.cmd_build(domain, dry_run=True)
        # No defaults file produced.
        assert not (domain / "policy_facets" / "naming-defaults.yaml").exists()
        # No per-file rewrites.
        after = _read_per_file(domain, "b.md")
        assert before == after
        assert summary["files_rewritten"] == 0


# ---------------------------------------------------------------------------
# Synonym row ordering
# ---------------------------------------------------------------------------


def test_synonym_rows_sorted_by_name_source_doc_section():
    """Self-synonym rows are sorted by (name, source_doc, section). Canonical's
    source_doc/section come from the alphabetically-first observation."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        for rel in ("z_last.md", "a_first.md", "m_mid.md"):
            _write_per_file(
                domain, rel,
                naming_manifest={"variables": {"gross_income": {
                    "policy_phrase": "gross monthly income", "source_section": "§1",
                }}},
                sections=[{"heading": "# h", "summary": "", "tags": [],
                           "computations": [{"description": "", "variables": ["gross_income"]}]}],
            )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        # Top-level: alphabetically-first observation wins.
        assert entry["source_doc"] == "input/policy_docs/a_first.md"
        assert entry["section"] == "§1"
        # Remaining observations of the canonical name become self-synonym rows,
        # sorted by (name, source_doc, section). Same name → sort by source_doc.
        assert entry["synonyms"] == [
            {
                "name": "gross_income",
                "source_doc": "input/policy_docs/m_mid.md",
                "section": "§1",
            },
            {
                "name": "gross_income",
                "source_doc": "input/policy_docs/z_last.md",
                "section": "§1",
            },
        ]


# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# description / type / values resolution (R1, R2, R4, R5, R8)
# ---------------------------------------------------------------------------


def test_description_round_trips_from_per_file_to_defaults():
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income",
                "source_section": "§1",
                "description": "Total monthly household income before any deductions.",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert defaults["variables"]["gross_income"]["description"] == (
            "Total monthly household income before any deductions."
        )


def test_type_money_round_trips_from_per_file_to_defaults():
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income",
                "source_section": "§1",
                "type": "money",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert defaults["variables"]["gross_income"]["type"] == "money"
        assert "values" not in defaults["variables"]["gross_income"]


def test_type_enum_with_values_round_trips_from_single_file():
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"eligibility": {
                "policy_phrase": "eligibility status",
                "source_section": "§1",
                "type": "enum",
                "values": ["approve", "deny", "manual_verification"],
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["eligibility"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["eligibility"]
        assert entry["type"] == "enum"
        assert entry["values"] == ["approve", "deny", "manual_verification"]


def test_two_files_agree_on_type_money_canonical_carries_it():
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        for rel in ("a.md", "b.md"):
            _write_per_file(
                domain, rel,
                naming_manifest={"variables": {"gross_income": {
                    "policy_phrase": "gross monthly income",
                    "source_section": "§1",
                    "type": "money",
                }}},
                sections=[{"heading": "# h", "summary": "", "tags": [],
                           "computations": [{"description": "", "variables": ["gross_income"]}]}],
            )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert defaults["variables"]["gross_income"]["type"] == "money"


def test_enum_values_union_across_synonyms_sorted():
    """Two synonyms each carry overlapping values; canonical's values: is the sorted union."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"status": {
                "policy_phrase": "decision status",
                "source_section": "§1",
                "type": "enum",
                "values": ["approve", "deny"],
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["status"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"decision": {
                "policy_phrase": "decision status",
                "source_section": "§2",
                "type": "enum",
                "values": ["deny", "manual_verification"],
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["decision"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        # Canonical winner: "status" (frequency tie 1=1, shortest tie 6=8 → status wins).
        canonical_name = "decision" if "decision" in defaults["variables"] else "status"
        assert defaults["variables"][canonical_name]["type"] == "enum"
        assert defaults["variables"][canonical_name]["values"] == [
            "approve", "deny", "manual_verification",
        ]


def test_specs_overrides_observed_type_and_description():
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income",
                "source_section": "§1",
                "type": "money",
                "description": "AI-emitted description.",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_specs(domain, {
            "inputs": {
                "Household": {
                    "gross_income": {
                        "policy_phrase": "gross monthly income",
                        "type": "int",
                        "description": "Analyst-confirmed override.",
                    },
                },
            },
        })
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert entry["type"] == "int"
        assert entry["description"] == "Analyst-confirmed override."


def test_specs_values_override_observed_values():
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"status": {
                "policy_phrase": "decision status",
                "source_section": "§1",
                "type": "enum",
                "values": ["yes", "no"],
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["status"]}]}],
        )
        _write_specs(domain, {
            "outputs": {
                "status": {
                    "policy_phrase": "decision status",
                    "type": "enum",
                    "values": ["approve", "deny", "pending"],
                },
            },
        })
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        # Specs values override observed values.
        assert defaults["variables"]["status"]["values"] == ["approve", "deny", "pending"]


def test_disagreeing_observed_types_omitted_with_warning():
    """Two synonyms disagree on type; canonical entry has no type field, errors carries warning."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"amount": {
                "policy_phrase": "shared phrase",
                "source_section": "§1",
                "type": "money",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["amount"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"value": {
                "policy_phrase": "shared phrase",
                "source_section": "§2",
                "type": "int",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["value"]}]}],
        )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        # Canonical winner is the alphabetically-first (frequency tie, length tie).
        canonical = "amount"  # tied freq, shorter len than 'value' (6=5? no, 6>5). Let's check...
        # Lengths: amount=6, value=5. 'value' wins (shortest).
        canonical = "value"
        assert canonical in defaults["variables"]
        assert "type" not in defaults["variables"][canonical]
        # Warning surfaces in errors.
        warnings = [e for e in summary["errors"] if "types disagree" in e]
        assert len(warnings) == 1
        assert "money" in warnings[0]
        assert "int" in warnings[0]


def test_description_falls_back_to_synonym_when_canonical_lacks_one():
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # 'gi' wins canonical (shortest), no description; 'gross_income' synonym has description.
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gi": {
                "policy_phrase": "gross monthly income",
                "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gi"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income",
                "source_section": "§2",
                "description": "Synonym description filled in.",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert "gi" in defaults["variables"]
        assert defaults["variables"]["gi"]["description"] == "Synonym description filled in."


def test_canonical_contributor_description_preferred_over_synonym():
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # Both files use the same name 'gross_income' (frequency 2 → wins). The
        # synonym 'monthly_gross' from a third file has its own description
        # that should NOT win because the canonical contributor has one.
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income",
                "source_section": "§1",
                "description": "Canonical-side description.",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income",
                "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "c.md",
            naming_manifest={"variables": {"monthly_gross": {
                "policy_phrase": "gross monthly income",
                "source_section": "§3",
                "description": "Synonym-side description.",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["monthly_gross"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        assert defaults["variables"]["gross_income"]["description"] == "Canonical-side description."


def test_legacy_per_file_without_new_fields_merges_cleanly():
    """R8 regression guard: existing per-file files (no description/type/values) keep working."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income",
                "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert "description" not in entry
        assert "type" not in entry
        assert "values" not in entry
        assert entry["policy_phrase"] == "gross monthly income"


def test_idempotent_with_new_fields():
    """Two consecutive --build runs produce byte-identical output even with new fields populated."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"status": {
                "policy_phrase": "decision status",
                "source_section": "§1",
                "type": "enum",
                "values": ["b", "a", "c"],  # unsorted intentionally
                "description": "Outcome of the decision rule.",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["status"]}]}],
        )
        naming_defaults.cmd_build(domain)
        first = (domain / "policy_facets" / "naming-defaults.yaml").read_bytes()
        naming_defaults.cmd_build(domain)
        second = (domain / "policy_facets" / "naming-defaults.yaml").read_bytes()
        assert first == second, "non-deterministic output across runs"
        defaults = _read_defaults(domain)
        # Values are sorted in output.
        assert defaults["variables"]["status"]["values"] == ["a", "b", "c"]


def test_field_order_in_output_yaml():
    """Field insertion order: description, policy_phrase, type, values, role_hint, source_doc, section, synonyms."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"status": {
                "policy_phrase": "decision status",
                "source_section": "§1",
                "role_hint": "output",
                "type": "enum",
                "values": ["a", "b"],
                "description": "Outcome.",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["status"]}]}],
        )
        # Add a synonym observation so synonyms: appears in output.
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"decision_status": {
                "policy_phrase": "decision status",
                "source_section": "§2",
                "type": "enum",
                "values": ["a", "b"],
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["decision_status"]}]}],
        )
        naming_defaults.cmd_build(domain)
        text = (domain / "policy_facets" / "naming-defaults.yaml").read_text()
        # Within the canonical's block, find each field's position.
        positions = {}
        for field in ("description:", "policy_phrase:", "type:", "values:",
                      "role_hint:", "source_doc:", "section:", "synonyms:"):
            positions[field] = text.find(field)
            assert positions[field] != -1, f"field {field!r} missing from output"
        order = [
            "description:", "policy_phrase:", "type:", "values:",
            "role_hint:", "source_doc:", "section:", "synonyms:",
        ]
        for a, b in zip(order, order[1:]):
            assert positions[a] < positions[b], (
                f"field {a!r} at {positions[a]} should precede {b!r} at {positions[b]}"
            )
        # `sources:` is gone from the schema entirely.
        assert "sources:" not in text


# ---------------------------------------------------------------------------
# New schema: self-synonyms, multi-source synonyms, specs fallback, metrics
# ---------------------------------------------------------------------------


def test_canonical_appearing_in_multiple_files_emits_self_synonyms():
    """R3: canonical observed in 2 (file, section) pairs → first wins top-level,
    extras become self-synonym rows (name == canonical)."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§A",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§B",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert entry["source_doc"] == "input/policy_docs/a.md"
        assert entry["section"] == "§A"
        assert entry["synonyms"] == [{
            "name": "gross_income",
            "source_doc": "input/policy_docs/b.md",
            "section": "§B",
        }]


def test_multi_source_synonym_emits_one_row_per_observation():
    """R4: a single synonym name observed in two distinct (file, section) pairs
    produces two synonym rows (no dedup of distinct sources)."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # Anchor the canonical pick via specs so it doesn't depend on a freq
        # distribution that loses to the multi-source synonym.
        _write_specs(domain, {
            "version": "1.0",
            "computed": {
                "gi": {
                    "policy_phrase": "gross monthly income",
                    "source_doc": "canonical.md",
                    "section": "§1",
                },
            },
        })
        # Canonical 'gi' (specs-anchored) appears once in observations.
        _write_per_file(
            domain, "canonical.md",
            naming_manifest={"variables": {"gi": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gi"]}]}],
        )
        # Synonym 'gross_income' in two distinct (file, section) pairs.
        _write_per_file(
            domain, "syn_a.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§A",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        _write_per_file(
            domain, "syn_b.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§B",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gi"]
        assert entry["synonyms"] == [
            {
                "name": "gross_income",
                "source_doc": "input/policy_docs/syn_a.md",
                "section": "§A",
            },
            {
                "name": "gross_income",
                "source_doc": "input/policy_docs/syn_b.md",
                "section": "§B",
            },
        ]


def test_canonical_source_picks_first_alphabetical_observation():
    """When the canonical name has multiple observations, the (file, section)
    sort key picks deterministically — file first, then section."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # Same file, two sections — section sort key picks §1 over §2.
        _write_per_file(
            domain, "shared.md",
            naming_manifest={"variables": {"gi": {
                "policy_phrase": "gross monthly income", "source_section": "§2",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gi"]}]}],
        )
        # Lower-alphabet file beats higher even when section is "later".
        _write_per_file(
            domain, "alpha.md",
            naming_manifest={"variables": {"gi": {
                "policy_phrase": "gross monthly income", "source_section": "§99",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gi"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gi"]
        assert entry["source_doc"] == "input/policy_docs/alpha.md"
        assert entry["section"] == "§99"


def test_specs_picked_canonical_with_no_observation_falls_back_to_specs_source():
    """Specs supplies the canonical name; no per-file file observes it. Top-level
    source_doc/section come from specs; synonyms list every observation (no
    canonical-observation to exclude)."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_specs(domain, {
            "version": "1.0",
            "computed": {
                "specs_only_canonical": {
                    "policy_phrase": "the concept",
                    "source_doc": "input/policy_docs/spec_doc.md",
                    "section": "§spec",
                },
            },
        })
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"alt_one": {
                "policy_phrase": "the concept", "source_section": "§A",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["alt_one"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"alt_two": {
                "policy_phrase": "the concept", "source_section": "§B",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["alt_two"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["specs_only_canonical"]
        assert entry["source_doc"] == "input/policy_docs/spec_doc.md"
        assert entry["section"] == "§spec"
        assert entry["synonyms"] == [
            {"name": "alt_one", "source_doc": "input/policy_docs/a.md", "section": "§A"},
            {"name": "alt_two", "source_doc": "input/policy_docs/b.md", "section": "§B"},
        ]


def test_specs_basename_normalized_to_full_path():
    """Specs `source_doc:` is conventionally a basename like 'eligibility.md'.
    R6 mandates full-path everywhere → prepend input/policy_docs/."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_specs(domain, {
            "version": "1.0",
            "computed": {
                "concept_canonical": {
                    "policy_phrase": "some concept",
                    "source_doc": "eligibility.md",  # bare basename
                    "section": "§1",
                },
            },
        })
        _write_per_file(
            domain, "other.md",
            naming_manifest={"variables": {"observed_alt": {
                "policy_phrase": "some concept", "source_section": "§other",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["observed_alt"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["concept_canonical"]
        # Bare basename gets prepended with input/policy_docs/.
        assert entry["source_doc"] == "input/policy_docs/eligibility.md"


def test_synonyms_collapsed_metric_counts_unique_names_not_rows():
    """R10: synonyms_collapsed counts unique non-canonical names per entry,
    not synonym row count. Self-synonym rows + multi-source duplicates of one
    name must not inflate the count."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # Canonical 'gi' observed in 3 files (1 wins top-level + 2 self-synonyms).
        for rel, sect in (("a.md", "§1"), ("b.md", "§2"), ("c.md", "§3")):
            _write_per_file(
                domain, rel,
                naming_manifest={"variables": {"gi": {
                    "policy_phrase": "gross monthly income", "source_section": sect,
                }}},
                sections=[{"heading": "# h", "summary": "", "tags": [],
                           "computations": [{"description": "", "variables": ["gi"]}]}],
            )
        # Synonym 'gross_income' observed in 3 distinct files.
        for rel, sect in (("d.md", "§1"), ("e.md", "§2"), ("f.md", "§3")):
            _write_per_file(
                domain, rel,
                naming_manifest={"variables": {"gross_income": {
                    "policy_phrase": "gross monthly income", "source_section": sect,
                }}},
                sections=[{"heading": "# h", "summary": "", "tags": [],
                           "computations": [{"description": "", "variables": ["gross_income"]}]}],
            )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gi"]
        # 5 synonym rows total: 2 self-synonyms + 3 alternate-name rows.
        assert len(entry["synonyms"]) == 5
        # But synonyms_collapsed counts unique non-canonical names → 1 ('gross_income').
        assert summary["synonyms_collapsed"] == 1


def test_section_omitted_when_empty_top_level_and_in_synonym_row():
    """Empty source_section in observations → no section: key emitted (top-level
    or inside a synonym row). source_doc: still present."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gi": {
                "policy_phrase": "gross monthly income", "source_section": "",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gi"]}]}],
        )
        _write_per_file(
            domain, "b.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gi"]
        # Top-level: source_doc present, section absent.
        assert entry["source_doc"] == "input/policy_docs/a.md"
        assert "section" not in entry
        # Synonym row: source_doc present, section absent.
        assert entry["synonyms"] == [
            {"name": "gross_income", "source_doc": "input/policy_docs/b.md"},
        ]


def test_same_name_distinct_empty_vs_present_section_yields_two_rows():
    """Two observations of the same synonym name in the same file — one empty
    section, one populated. The dedup key is (name, source_doc, section), so
    these are distinct rows."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # Anchor canonical 'gi' via specs (synonym 'gross_income' observed twice
        # would otherwise win frequency).
        _write_specs(domain, {
            "version": "1.0",
            "computed": {
                "gi": {
                    "policy_phrase": "gross monthly income",
                    "source_doc": "canon.md",
                    "section": "§canon",
                },
            },
        })
        # Canonical from a different file.
        _write_per_file(
            domain, "canon.md",
            naming_manifest={"variables": {"gi": {
                "policy_phrase": "gross monthly income", "source_section": "§canon",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gi"]}]}],
        )
        # The per-file YAML schema has one variable name per map entry, so
        # the duplicate-name-with-different-section case has to come from
        # separate per-file files — feed two files that share a name and
        # differ only in section.
        # File with empty section:
        _write_per_file(
            domain, "syn_empty.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        # File with populated section:
        _write_per_file(
            domain, "syn_filled.md",
            naming_manifest={"variables": {"gross_income": {
                "policy_phrase": "gross monthly income", "source_section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gross_income"]}]}],
        )
        naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gi"]
        # Two distinct synonym rows (empty section vs §1).
        assert len(entry["synonyms"]) == 2
        names = sorted({r["name"] for r in entry["synonyms"]})
        assert names == ["gross_income"]


# ---------------------------------------------------------------------------
# Per-file source_doc / section schema (R3, R5, R6)
# ---------------------------------------------------------------------------


def test_legacy_source_section_emits_warning():
    """Per-file file with legacy `source_section:` (no `section:`, no
    `source_doc:`) produces an actionable warning in summary['errors'].
    The build still completes; output entry has no section field."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # Bypass _write_per_file's auto-migration; write raw legacy YAML.
        dst = domain / "policy_facets" / "computations" / "legacy.md.yaml"
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(
            "# Auto-generated by /extract-computations — do not edit manually\n"
            "# Source: input/policy_docs/legacy.md\n\n"
            "naming_manifest:\n"
            "  variables:\n"
            "    gross_income:\n"
            "      policy_phrase: \"gross monthly income\"\n"
            "      source_section: \"§1.2\"\n"
            "sections: []\n",
            encoding="utf-8",
        )
        summary = naming_defaults.cmd_build(domain)
        legacy_warnings = [
            e for e in summary["errors"] if "legacy 'source_section:'" in e
        ]
        assert len(legacy_warnings) == 1
        assert "gross_income" in legacy_warnings[0]
        assert "delete and re-run /extract-computations" in legacy_warnings[0]
        # Build still completes; output entry has no section.
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert "section" not in entry
        # source_doc falls back to file location.
        assert entry["source_doc"] == "input/policy_docs/legacy.md"


def test_drift_warning_when_source_doc_disagrees_with_location():
    """Per-file file's source_doc disagrees with file location → drift warning;
    build uses worker-written value verbatim."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        dst = domain / "policy_facets" / "computations" / "actual.md.yaml"
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(
            "# Auto-generated by /extract-computations — do not edit manually\n"
            "# Source: input/policy_docs/actual.md\n\n"
            "naming_manifest:\n"
            "  variables:\n"
            "    gross_income:\n"
            "      policy_phrase: \"gross monthly income\"\n"
            "      source_doc: \"input/policy_docs/different.md\"\n"
            "      section: \"§1.2\"\n"
            "sections: []\n",
            encoding="utf-8",
        )
        summary = naming_defaults.cmd_build(domain)
        drift_warnings = [
            e for e in summary["errors"]
            if "disagrees with file location" in e
        ]
        assert len(drift_warnings) == 1
        assert "different.md" in drift_warnings[0]
        assert "actual.md" in drift_warnings[0]
        # Worker's source_doc wins verbatim.
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert entry["source_doc"] == "input/policy_docs/different.md"


def test_synonym_row_source_doc_from_entry_not_path():
    """When two observations of the same canonical exist, each synonym row's
    source_doc comes from its per-file entry (verbatim) — even when the entry
    declares a non-default source_doc that disagrees with file location."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        # Canonical observation at a.md, normal source_doc.
        _write_per_file(
            domain, "a.md",
            naming_manifest={"variables": {"gi": {
                "policy_phrase": "gross income", "section": "§1",
            }}},
            sections=[{"heading": "# h", "summary": "", "tags": [],
                       "computations": [{"description": "", "variables": ["gi"]}]}],
        )
        # Synonym observation at b.md but with source_doc declared as c.md.
        # Drift warning expected; synonym row carries c.md verbatim.
        dst_b = domain / "policy_facets" / "computations" / "b.md.yaml"
        dst_b.parent.mkdir(parents=True, exist_ok=True)
        dst_b.write_text(
            "# Auto-generated by /extract-computations — do not edit manually\n"
            "# Source: input/policy_docs/b.md\n\n"
            "naming_manifest:\n"
            "  variables:\n"
            "    gi_alt:\n"
            "      policy_phrase: \"gross income\"\n"
            "      source_doc: \"input/policy_docs/c.md\"\n"
            "      section: \"§2\"\n"
            "sections:\n"
            "  - heading: '# h'\n"
            "    summary: ''\n"
            "    tags: []\n"
            "    computations:\n"
            "      - description: ''\n"
            "        variables: [gi_alt]\n",
            encoding="utf-8",
        )
        summary = naming_defaults.cmd_build(domain)
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gi"]
        # Top-level source_doc from canonical observation (a.md, no drift).
        assert entry["source_doc"] == "input/policy_docs/a.md"
        # Synonym row source_doc verbatim from b.md's entry (which says c.md).
        assert entry["synonyms"] == [{
            "name": "gi_alt",
            "source_doc": "input/policy_docs/c.md",
            "section": "§2",
        }]
        # Drift warning emitted.
        drift_warnings = [
            e for e in summary["errors"]
            if "disagrees with file location" in e
        ]
        assert len(drift_warnings) == 1


def test_missing_source_doc_without_legacy_emits_warning():
    """Per-file file with no `source_doc:` and no `source_section:` (truly empty)
    falls back to path-derived source_doc and emits 'missing' warning."""
    with tempfile.TemporaryDirectory() as tmp:
        domain = _make_domain(Path(tmp))
        dst = domain / "policy_facets" / "computations" / "incomplete.md.yaml"
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(
            "# Auto-generated by /extract-computations — do not edit manually\n"
            "# Source: input/policy_docs/incomplete.md\n\n"
            "naming_manifest:\n"
            "  variables:\n"
            "    gross_income:\n"
            "      policy_phrase: \"gross monthly income\"\n"
            "sections: []\n",
            encoding="utf-8",
        )
        summary = naming_defaults.cmd_build(domain)
        missing_warnings = [
            e for e in summary["errors"] if "missing 'source_doc:'" in e
        ]
        assert len(missing_warnings) == 1
        defaults = _read_defaults(domain)
        entry = defaults["variables"]["gross_income"]
        assert entry["source_doc"] == "input/policy_docs/incomplete.md"


def main() -> int:
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failed = []
    for test in tests:
        try:
            test()
            print(f"PASS  {test.__name__}")
        except AssertionError as exc:
            failed.append((test.__name__, f"AssertionError: {exc}"))
            print(f"FAIL  {test.__name__}: {exc}")
        except Exception as exc:  # noqa: BLE001
            failed.append((test.__name__, f"{type(exc).__name__}: {exc}"))
            print(f"ERROR {test.__name__}: {type(exc).__name__}: {exc}")
    print(f"\n{len(tests) - len(failed)}/{len(tests)} passed")
    return 0 if not failed else 1


if __name__ == "__main__":
    sys.exit(main())
