# /// script
# requires-python = ">=3.14"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Tests for emit_per_file_yaml.py — covers U2 per-file YAML emission.

Run: uv run xl-plugin/tools/test_emit_per_file_yaml.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

sys.path.insert(0, os.path.dirname(__file__))

import emit_per_file_yaml  # noqa: E402


# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------


def _minimal_payload(dst: Path, source_rel: str = "input/policy_docs/a.md") -> dict:
    return {
        "destination": str(dst),
        "source_rel": source_rel,
        "naming_manifest": {"variables": {}},
        "sections": [],
    }


def _payload_with_one_variable(dst: Path) -> dict:
    return {
        "destination": str(dst),
        "source_rel": "input/policy_docs/a.md",
        "naming_manifest": {
            "variables": {
                "gross_income": {
                    "policy_phrase": "gross monthly income",
                    "role_hint": "input",
                    "source_section": "§1.2",
                },
            },
        },
        "sections": [
            {
                "heading": "# Income",
                "summary": "Income rules.",
                "tags": ["income"],
                "computations": [
                    {
                        "description": "Sum of wages.",
                        "variables": ["gross_income"],
                    },
                ],
            },
        ],
    }


# ---------------------------------------------------------------------------
# Cross-block name-set invariant
# ---------------------------------------------------------------------------


def test_validates_every_section_variable_in_naming_manifest():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["sections"][0]["computations"][0]["variables"] = [
            "gross_income",
            "missing_var",  # not in naming_manifest.variables
        ]
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "missing_var" in str(exc)
        else:
            raise AssertionError("expected ValidationError for missing_var")


def test_passes_when_all_section_variables_present_in_manifest():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_variable(dst))
        assert dst.exists()


def test_empty_sections_and_empty_manifest_are_valid():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_minimal_payload(dst))
        assert dst.exists()


# ---------------------------------------------------------------------------
# YAML shape and round-trip
# ---------------------------------------------------------------------------


def test_emitted_yaml_is_a_top_level_map_with_naming_manifest_and_sections():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_variable(dst))
        loaded = yaml.safe_load(dst.read_text())
        assert isinstance(loaded, dict)
        assert set(loaded.keys()) == {"naming_manifest", "sections"}


def test_emitted_yaml_has_preamble_with_source_path():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_variable(dst))
        text = dst.read_text()
        assert "# Auto-generated by /extract-computations — do not edit manually" in text
        assert "# Source: input/policy_docs/a.md" in text


def test_round_trip_preserves_naming_manifest_structure():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        assert loaded["naming_manifest"] == payload["naming_manifest"]


def test_round_trip_preserves_sections_structure():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        assert loaded["sections"] == payload["sections"]


def test_quotes_policy_phrase_with_special_characters():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _minimal_payload(dst)
        payload["naming_manifest"]["variables"]["foo"] = {
            "policy_phrase": "applicant's gross income: monthly",
            "source_section": "§1",
        }
        # No section reference required if sections is empty
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        phrase = loaded["naming_manifest"]["variables"]["foo"]["policy_phrase"]
        assert phrase == "applicant's gross income: monthly"


# ---------------------------------------------------------------------------
# Optional field omission
# ---------------------------------------------------------------------------


def test_role_hint_omitted_when_absent_from_input():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _minimal_payload(dst)
        payload["naming_manifest"]["variables"]["foo"] = {
            "policy_phrase": "the foo amount",
            "source_section": "§1",
        }
        emit_per_file_yaml.emit(payload)
        text = dst.read_text()
        assert "role_hint" not in text


def test_role_hint_emitted_when_present():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_variable(dst))
        text = dst.read_text()
        assert "role_hint: input" in text


# ---------------------------------------------------------------------------
# New optional fields: description, type, values
# ---------------------------------------------------------------------------


def test_description_field_round_trips_when_present():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["description"] = (
            "Total monthly household income before any deductions."
        )
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        entry = loaded["naming_manifest"]["variables"]["gross_income"]
        assert entry["description"] == (
            "Total monthly household income before any deductions."
        )


def test_type_money_round_trips_without_values():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["type"] = "money"
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        entry = loaded["naming_manifest"]["variables"]["gross_income"]
        assert entry["type"] == "money"
        assert "values" not in entry


def test_type_enum_with_values_round_trips():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["type"] = "enum"
        payload["naming_manifest"]["variables"]["gross_income"]["values"] = [
            "approve",
            "deny",
            "manual_verification",
        ]
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        entry = loaded["naming_manifest"]["variables"]["gross_income"]
        assert entry["type"] == "enum"
        assert entry["values"] == ["approve", "deny", "manual_verification"]


def test_legacy_payload_without_new_fields_still_emits_cleanly():
    """R8 regression guard: existing per-file files without description/type/values
    continue to validate and emit as before."""
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_variable(dst))
        loaded = yaml.safe_load(dst.read_text())
        entry = loaded["naming_manifest"]["variables"]["gross_income"]
        assert "description" not in entry
        assert "type" not in entry
        assert "values" not in entry


def test_description_null_is_treated_as_absent():
    """None-valued description is stripped silently (consistent with role_hint behavior)."""
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["description"] = None
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        entry = loaded["naming_manifest"]["variables"]["gross_income"]
        assert "description" not in entry


def test_description_empty_string_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["description"] = ""
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "description" in str(exc)
            assert "non-empty" in str(exc)
        else:
            raise AssertionError("expected ValidationError for empty description")


def test_description_whitespace_only_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["description"] = "   "
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "description" in str(exc)
        else:
            raise AssertionError("expected ValidationError for whitespace-only description")


def test_type_str_is_rejected_with_helpful_vocabulary_message():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["type"] = "str"
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            msg = str(exc)
            assert "type" in msg
            assert "string" in msg  # tells the caller the right value
            assert "money" in msg
        else:
            raise AssertionError("expected ValidationError for type: str")


def test_type_enum_without_values_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["type"] = "enum"
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "enum" in str(exc)
            assert "values" in str(exc)
        else:
            raise AssertionError("expected ValidationError for enum without values")


def test_values_without_enum_type_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["type"] = "string"
        payload["naming_manifest"]["variables"]["gross_income"]["values"] = ["a"]
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "values" in str(exc)
            assert "enum" in str(exc)
        else:
            raise AssertionError("expected ValidationError for values without enum")


def test_values_empty_list_with_enum_is_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["type"] = "enum"
        payload["naming_manifest"]["variables"]["gross_income"]["values"] = []
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "values" in str(exc)
            assert "non-empty" in str(exc)
        else:
            raise AssertionError("expected ValidationError for empty values list")


def test_values_non_string_elements_are_rejected():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["type"] = "enum"
        payload["naming_manifest"]["variables"]["gross_income"]["values"] = [1, 2, 3]
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError as exc:
            assert "values" in str(exc)
            assert "string" in str(exc)
        else:
            raise AssertionError("expected ValidationError for non-string values")


def test_all_eight_types_in_vocabulary_pass_validation():
    """Each of the eight CIVIL types is accepted (with values when enum)."""
    for t in ("money", "bool", "int", "float", "string", "list", "date"):
        with tempfile.TemporaryDirectory() as tmp:
            dst = Path(tmp) / "out.md.yaml"
            payload = _payload_with_one_variable(dst)
            payload["naming_manifest"]["variables"]["gross_income"]["type"] = t
            emit_per_file_yaml.emit(payload)
            loaded = yaml.safe_load(dst.read_text())
            assert loaded["naming_manifest"]["variables"]["gross_income"]["type"] == t

    # enum requires values
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["naming_manifest"]["variables"]["gross_income"]["type"] = "enum"
        payload["naming_manifest"]["variables"]["gross_income"]["values"] = ["a", "b"]
        emit_per_file_yaml.emit(payload)
        loaded = yaml.safe_load(dst.read_text())
        assert loaded["naming_manifest"]["variables"]["gross_income"]["type"] == "enum"


# ---------------------------------------------------------------------------
# Atomic write
# ---------------------------------------------------------------------------


def test_destination_does_not_get_partial_content_on_validation_failure():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        # Pre-populate destination with known content
        dst.write_text("PRIOR CONTENT\n")
        payload = _payload_with_one_variable(dst)
        payload["sections"][0]["computations"][0]["variables"] = ["missing_var"]
        try:
            emit_per_file_yaml.emit(payload)
        except emit_per_file_yaml.ValidationError:
            pass
        # Destination should be unchanged
        assert dst.read_text() == "PRIOR CONTENT\n"


def test_destination_creates_intermediate_directories():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "deeply" / "nested" / "out.md.yaml"
        emit_per_file_yaml.emit(_payload_with_one_variable(dst))
        assert dst.exists()


# ---------------------------------------------------------------------------
# CLI / stdin contract
# ---------------------------------------------------------------------------


def test_cli_reads_json_from_stdin_and_writes_yaml():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        result = subprocess.run(
            [sys.executable, os.path.join(os.path.dirname(__file__), "emit_per_file_yaml.py")],
            input=json.dumps(payload),
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, f"stderr: {result.stderr}"
        assert dst.exists()


def test_cli_exits_nonzero_on_validation_error():
    with tempfile.TemporaryDirectory() as tmp:
        dst = Path(tmp) / "out.md.yaml"
        payload = _payload_with_one_variable(dst)
        payload["sections"][0]["computations"][0]["variables"] = ["missing"]
        result = subprocess.run(
            [sys.executable, os.path.join(os.path.dirname(__file__), "emit_per_file_yaml.py")],
            input=json.dumps(payload),
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode != 0
        assert "missing" in result.stderr


# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    failed = 0
    passed = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
            except AssertionError as exc:
                failed += 1
                print(f"FAIL {name}: {exc}")
            except Exception as exc:
                failed += 1
                print(f"ERROR {name}: {type(exc).__name__}: {exc}")
            else:
                passed += 1
                print(f"ok {name}")
    print(f"\n{passed} passed, {failed} failed")
    sys.exit(1 if failed else 0)
